# Settings for Netlify CMS
# full guide for Gatsby & Netlify CMS here: https://www.gatsbyjs.org/docs/netlify-cms/

backend:
  name: git-gateway
  repo: ysdn2018/the-next-website

media_folder: src/content/assets
public_folder: assets

# CMS File Structures
collections:
  - name: graduates
    label: Graduates
    folder: src/content/graduates
    create: true
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: graduate}
      - { name: title, label: Name }
      - { name: image, label: Headshot, widget: image }
      - { name: verb, label: Statement Verb }
      - { name: noun, label: Statement Noun }
  - name: projects
    label: Projects
    folder: src/content/work
    create: true
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: project}
      - { name: title, label: Title }
      - { name: graduate, label: Graduate, widget: relation, collection: graduates, searchFields: ["title"], valueField: "title"}
      - { name: image, label: Thumbnail, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    files:
      - name: about
        label: About Page
        file: src/content/about.md
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: post}
          - { name: path, label: Path }
          - { name: title, label: Title }
          - { name: subtitle, label: Subtitle }
          - { name: image, label: Image, widget: image }
          - { name: description, label: Description, widget: text }
          - { name: body, label: Body, widget: markdown }
          - label: Example List
            name: exampleList
            widget: list
            fields:
              - { name: text, label: Text, widget: string }
