# Settings for Netlify CMS
# full guide for Gatsby & Netlify CMS here: https://www.gatsbyjs.org/docs/netlify-cms/

backend:
  name: git-gateway
  repo: ysdn2018/the-next-website

media_folder: src/content/assets
public_folder: assets
accept_roles: #optional - accepts all users if left out
  - admin
  - editor
# publish_mode: editorial_workflow

# CMS File Structures
collections:
  - name: graduates
    label: Graduates
    folder: src/content/graduates
    create: true
    # editor: 
    #  preview: false 
    # pattern: ['^(?:\b\w+\b[\s\r\n]*){1,250}$', "Max word count of 250"] 
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: graduate}
      - { name: title, label: Your Name }
      - { name: headshot, label: Headshot, widget: hidden, default: "/assets/sloth.jpg" }
      - { name: headshotHover, label: Headshot Hover, widget: hidden, default: "/assets/sloth2.jpg" }
      - { name: verb, label: Statement Verb }
      - { name: noun, label: Statement Noun }
      - { name: intro, label: Intro (third-person), widget: text, required: false }
      - { name: hobbies, label: Hobbies (optional), widget: text, required: false }
      - { name: music, label: Fav Music (optional), widget: text, required: false }
      - { name: tools, label: Design Tools (optional), widget: text, required: false }
      - { name: watch, label: Fav Movies/TV (optional), widget: text, required: false }
      - { name: typeface, label: Fav Typeface (optional), widget: text, required: false }
      - { name: twitter, label: Twitter (link)(optional), required: false}
      - { name: instagram, label: Instagram (link)(optional), required: false}
      - { name: linkedin, label: Linkedin (link)(optional), required: false}
      - { name: email, label: Email (link)(optional), required: false}
      - { name: website, label: Personal Website (link)(optional), required: false}
  - name: projects
    label: Projects
    folder: src/content/work
    create: true
    editor: 
     preview: false 
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: project}
      - { name: title, label: Project Title }
      - { name: graduate, label: "Your Name (make sure it's consistent with your name on your profile so the links work)", widget: relation, collection: graduates, searchFields: ["title"], valueField: "title"}
      - { name: image, label: Feature Image (2mb Max - large (2000px+) will be auto-cropped square & landscape), widget: image }
      - name: category
        label: Category
        widget: select
        options: ["Choose...", "Package Design", "Installation", "Environmental Design", "Editorial Design", "Book Design", "Information Design", "Typography", "UI/UX", "Product Design", "Motion Design", "Time Based Communication", "Web Design", "Information Design", "Brand Identity", "Communication Design", "Experiential Design"]
        default: "Choose..."
      - name: category2
        label: Additional Category (optional)
        widget: select
        options: ["Package Design", "Installation", "Environmental Design", "Editorial Design", "Book Design", "Information Design", "Typography", "UI/UX", "Product Design", "Motion Design", "Time Based Communication", "Web Design", "Information Design", "Brand Identity", "Communication Design", "Experiential Design"]
        required: false
      - name: category3
        label: Additional Category (optional)
        widget: select
        options: ["Package Design", "Installation", "Environmental Design", "Editorial Design", "Book Design", "Information Design", "Typography", "UI/UX", "Product Design", "Motion Design", "Time Based Communication", "Web Design", "Information Design", "Brand Identity", "Communication Design", "Experiential Design"]
        required: false


      - { name: body, label: Body, widget: markdown }
      # - { name: category, label: Category, widget: select, options: ["Design Memes", "Something Else", "Other Memes", "Selfies"], default: Choose}


  - name: pages
    label: Info Pages
    files:
      - name: about
        label: About Page
        file: src/content/about.md
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: post}
          - { name: path, label: Path }
          - { name: title, label: Title }
          - { name: subtitle, label: Subtitle }
          - { name: image, label: Image, widget: image }
          - { name: description, label: Description, widget: text }
          - { name: body, label: Body, widget: markdown }
          - label: Example List
            name: exampleList
            widget: list
            fields:
              - { name: text, label: Text, widget: string }
